services:
  - type: web
    name: foodfixr-scanner
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      apt-get update && 
      apt-get install -y tesseract-ocr tesseract-ocr-eng && 
      apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 &&
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_WEEKLY_PRICE_ID
        sync: false
      - key: STRIPE_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_YEARLY_PRICE_ID
        sync: false
      - key: DOMAIN
        value: https://foodfixr-scanner.onrender.com
