services:
  - type: web
    name: foodfixr-scanner
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔧 Starting build process..."
      apt-get update -y
      apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev libleptonica-dev
      echo "📦 Tesseract packages installed"
      which tesseract
      tesseract --version
      echo "✅ Tesseract verification complete"
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "🐍 Python packages installed"
      echo "🎉 Build complete!"
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_WEEKLY_PRICE_ID
        sync: false
      - key: STRIPE_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_YEARLY_PRICE_ID
        sync: false
      - key: DOMAIN
        value: https://foodfixr-scanner.onrender.com
