# scanner_config.py
# Configuration file containing all ingredient lists based on hierarchy document

# Trans Fats - High Risk (ranks 1-10)
trans_fat_high_risk = [
    "partially hydrogenated oil",
    "partially hydrogenated soybean oil",
    "partially hydrogenated cottonseed oil",
    "partially hydrogenated palm oil",
    "partially hydrogenated canola oil",
    "vegetable shortening",
    "shortening",
    "hydrogenated oil",
    "interesterified fats",
    "high-stability oil"
]

# Trans Fats - Moderate Risk (ranks 11-18)
trans_fat_moderate_risk = [
    "hydrogenated fat",
    "margarine",
    "vegetable oil",
    "blended vegetable oil",
    "frying oil",
    "modified fat",
    "synthetic fat",
    "lard substitute",
    "monoglycerides",
    "diglycerides",
    "monoglycerides/diglycerides",
    "mono- and diglycerides"
]

# Trans Fats - Safe (ranks 19-23)
trans_fat_safe = [
    "fully hydrogenated oil",
    "palm oil",
    "palm oil (non-hydrogenated)",
    "coconut oil",
    "butter",
    "ghee",
    "butter/ghee",
    "cold-pressed oil",
    "cold-pressed oils",
    "olive oil",
    "avocado oil",
    "walnut oil"
]

# Excitotoxins - High Risk (ranks 1-10)
excitotoxin_high_risk = [
    "monosodium glutamate",
    "msg",
    "aspartame",
    "equal",
    "nutrasweet",
    "hydrolyzed vegetable protein",
    "hvp",
    "hydrolyzed soy protein",
    "hydrolyzed corn protein",
    "disodium inosinate",
    "disodium guanylate",
    "yeast extract",
    "natural yeast extract",
    "extract of yeast",
    "autolyzed yeast",
    "calcium caseinate",
    "sodium caseinate",
    "torula yeast"
]

# Excitotoxins - Moderate Risk (ranks 11-16)
excitotoxin_moderate_risk = [
    "natural flavors",
    "natural flavoring",
    "spices",
    "seasonings",
    "spices/seasonings",
    "seasoning blends",
    "soy sauce",
    "non-brewed soy sauce",
    "hydrolyzed soy sauce",
    "enzyme modified cheese",
    "whey protein isolate",
    "whey protein hydrolysate",
    "bouillon",
    "broth",
    "stock",
    "chicken broth",
    "beef stock",
    "bouillon flavor"
]

# Excitotoxins - Low Risk/Ambiguous (ranks 17-21)
excitotoxin_low_risk = [
    "maltodextrin",
    "modified food starch",
    "textured vegetable protein",
    "tvp",
    "corn syrup solids",
    "carrageenan"
]

# Corn - High Risk (ranks 1-16)
corn_high_risk = [
    "high fructose corn syrup",
    "hfcs",
    "corn syrup",
    "cornstarch",
    "corn starch",
    "modified cornstarch",
    "modified corn starch",
    "maltodextrin",
    "dextrose",
    "fructose",
    "glucose",
    "citric acid",
    "ascorbic acid",
    "erythritol",
    "sorbitol",
    "xylitol",
    "caramel color",
    "vanillin",
    "msg",  # when derived from corn
    "monosodium glutamate"  # when derived from corn
]

# Corn - Moderate Risk (ranks 17-30)
corn_moderate_risk = [
    "natural flavors",
    "natural flavoring",
    "vegetable oil",
    "vegetable starch",
    "modified food starch",
    "lactic acid",
    "xanthan gum",
    "guar gum",
    "enzymes",
    "lecithin",
    "tocopherols",
    "vitamin e",
    "baking powder",
    "polydextrose",
    "inositol",
    "mono- and diglycerides",
    "monoglycerides",
    "diglycerides",
    "calcium stearate",
    "magnesium stearate"
]

# Corn - Low Risk (ranks 31-39)
corn_low_risk = [
    "sodium erythorbate",
    "ethyl maltol",
    "sodium citrate",
    "potassium citrate",
    "masa harina",
    "corn meal",
    "corn flour",
    "corn oil",
    "corn alcohol",
    "corn ethanol",
    "pla",
    "corn-based vinegars",
    "white vinegar",
    "sorbitan monooleate",
    "sorbitan tristearate",
    "zein"
]

# Sugar - All sugar ingredients count as problematic
sugar_keywords = [
    # High Risk Sugars (1-15)
    "high-fructose corn syrup",
    "high fructose corn syrup",
    "hfcs",
    "corn syrup",
    "corn syrup solids",
    "glucose-fructose syrup",
    "crystalline fructose",
    "anhydrous dextrose",
    "invert sugar",
    "maltodextrin",
    "glucose solids",
    "refiner's syrup",
    "refiners syrup",
    "agave syrup",
    "agave nectar",
    "fructose",
    "dextrose",
    "glucose",
    "sucrose",
    
    # Moderate/Low Risk Sugars (16-58)
    "cane sugar",
    "beet sugar",
    "brown sugar",
    "coconut sugar",
    "date sugar",
    "palm sugar",
    "evaporated cane juice",
    "fruit juice concentrate",
    "fruit juice concentrates",
    "apple juice concentrate",
    "grape juice concentrate",
    "pear juice concentrate",
    "barley malt syrup",
    "brown rice syrup",
    "rice syrup",
    "golden syrup",
    "sorghum syrup",
    "molasses",
    "treacle",
    "carob syrup",
    "yacon syrup",
    "honey",
    "maple syrup",
    "maple sugar",
    "coconut nectar",
    "date syrup",
    "date paste",
    "banana puree",
    "raisin juice concentrate",
    "fig paste",
    "grape must",
    "apple puree",
    "pineapple juice concentrate",
    "diastatic malt",
    "malt syrup",
    "malt extract",
    "ethyl maltol",
    
    # Ambiguous/Marketing terms
    "organic cane juice",
    "dehydrated cane juice",
    "cane juice crystals",
    "rice sweetener",
    "natural sweetener",
    "all-natural sweetener",
    "naturally sweetened",
    "sweetened",
    "sugar"
]

# GMO ingredients (not part of ranking but flagged separately)
gmo_keywords = [
    "corn syrup",
    "high fructose corn syrup",
    "hfcs",
    "corn starch",
    "cornstarch",
    "modified corn starch",
    "modified cornstarch",
    "soybean oil",
    "soy lecithin",
    "soy protein isolate",
    "canola oil",
    "cottonseed oil",
    "textured vegetable protein",
    "tvp",
    "hydrolyzed soy protein",
    "hydrolyzed vegetable protein",
    "sugar",  # when not specified as cane sugar
    "monoglycerides",
    "diglycerides",
    "mono- and diglycerides",
    "maltodextrin",
    "dextrose",
    "glucose",
    "fructose",
    "ascorbic acid",
    "citric acid",
    "xanthan gum",
    "natural flavors",
    "yeast extract",
    "heme",
    "soy leghemoglobin",
    "enzymes",
    "glycerin",
    "glycerol",
    "lactic acid",
    "sodium lactate",
    "tocopherols",
    "vitamin e",
    "modified food starch",
    "bioengineered food",
    "contains bioengineered ingredients",
    "fermentation-derived dairy proteins",
    "synbio vanillin",
    "vegetable oil",
    "starch",
    "modified starch",
    "lecithin",
    "flavoring",
    "natural flavor",
    "artificial flavor",
    "alcohol",
    "ethanol",
    "corn alcohol",
    "fruit juice concentrate",
    "papaya",
    "zucchini",
    "yellow summer squash",
    "arctic apple",
    "innate potato",
    "pink pineapple",
    "genetically engineered",
    "genetically modified organism",
    "gmo",
    "bioengineered",
    "fermentation-derived proteins",
    "synthetic biology",
    "synbio",
    "lab-grown",
    "precision fermentation"
]

# Safe ingredients
safe_ingredients = [
    # Safe fats
    "fully hydrogenated oil",
    "palm oil",
    "palm oil (non-hydrogenated)",
    "coconut oil",
    "butter",
    "ghee",
    "butter/ghee",
    "cold-pressed oil",
    "cold-pressed oils",
    "olive oil",
    "extra virgin olive oil",
    "avocado oil",
    "walnut oil",
    "almond oil",
    "sesame oil",
    "sunflower oil",
    "safflower oil",
    
    # Natural whole foods
    "water",
    "salt",
    "sea salt",
    "himalayan salt",
    "black pepper",
    "white pepper",
    "garlic",
    "onion",
    "ginger",
    "turmeric",
    "cinnamon",
    "paprika",
    "cumin",
    "coriander",
    "basil",
    "oregano",
    "thyme",
    "rosemary",
    "sage",
    "parsley",
    "cilantro",
    "mint",
    "dill",
    "bay leaves",
    "vanilla",
    "vanilla bean",
    "cocoa",
    "cacao",
    "coffee",
    "tea",
    
    # Safe additives
    "vitamin d",
    "vitamin d3",
    "calcium carbonate",
    "iron",
    "zinc",
    "magnesium",
    "potassium",
    "sodium bicarbonate",
    "baking soda",
    "cream of tartar",
    "pectin",
    "gelatin",
    "agar",
    "psyllium",
    "flax",
    "chia",
    
    # Whole grains and seeds
    "oats",
    "quinoa",
    "brown rice",
    "wild rice",
    "millet",
    "buckwheat",
    "amaranth",
    "teff",
    "sorghum",
    "barley",
    "rye",
    "spelt",
    "kamut",
    "wheat",
    "whole wheat",
    
    # Nuts and seeds
    "almonds",
    "walnuts",
    "pecans",
    "cashews",
    "pistachios",
    "macadamia",
    "hazelnuts",
    "brazil nuts",
    "pine nuts",
    "pumpkin seeds",
    "sunflower seeds",
    "sesame seeds",
    "flax seeds",
    "chia seeds",
    "hemp seeds",
    
    # Dairy
    "milk",
    "cream",
    "yogurt",
    "cheese",
    "cottage cheese",
    "ricotta",
    "mozzarella",
    "cheddar",
    "parmesan",
    "feta",
    
    # Proteins
    "eggs",
    "egg whites",
    "chicken",
    "turkey",
    "beef",
    "pork",
    "lamb",
    "fish",
    "salmon",
    "tuna",
    "shrimp",
    "crab",
    "lobster",
    
    # Vegetables
    "spinach",
    "kale",
    "lettuce",
    "arugula",
    "broccoli",
    "cauliflower",
    "cabbage",
    "brussels sprouts",
    "carrots",
    "celery",
    "cucumber",
    "tomatoes",
    "bell peppers",
    "mushrooms",
    "asparagus",
    "green beans",
    "peas",
    "corn",  # whole corn
    "potatoes",
    "sweet potatoes",
    "squash",
    "pumpkin",
    "eggplant",
    "beets",
    "radishes",
    "turnips",
    
    # Fruits
    "apples",
    "bananas",
    "oranges",
    "lemons",
    "limes",
    "grapefruit",
    "berries",
    "strawberries",
    "blueberries",
    "raspberries",
    "blackberries",
    "grapes",
    "melons",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "pineapple",
    "mango",
    "papaya",
    "kiwi",
    "peaches",
    "plums",
    "apricots",
    "cherries",
    "pears",
    "figs",
    "dates",
    "raisins",
    "cranberries",
    "pomegranate",
    "avocado",
    
    # Legumes
    "beans",
    "black beans",
    "pinto beans",
    "kidney beans",
    "navy beans",
    "chickpeas",
    "lentils",
    "split peas",
    "soybeans",
    "edamame",
    "tofu",
    "tempeh"
]

# Common OCR errors to fix
common_ocr_errors = {
    "corn5yrup": "corn syrup",
    "cornsynup": "corn syrup",
    "com syrup": "corn syrup",
    "hfc5": "hfcs",
    "m5g": "msg",
    "ms9": "msg",
    "aspartame": "aspartame",
    "aspertame": "aspartame",
    "hydrogenatedoil": "hydrogenated oil",
    "naturalflavors": "natural flavors",
    "modifiedstarch": "modified starch",
    "highfructose": "high fructose",
    "partiallyhydrogenated": "partially hydrogenated",
    "monosodiumglutamate": "monosodium glutamate",
    "yeastextract": "yeast extract",
    "soylecithin": "soy lecithin",
    "canolaoil": "canola oil",
    "cottonseedoil": "cottonseed oil",
    "cornsyrup": "corn syrup",
    "cornstarch": "corn starch",
    "dextrose": "dextrose",
    "maltodextrin": "maltodextrin",
    "naturalflavor": "natural flavor",
    "artificalflavor": "artificial flavor",
    "modifiedcornstarch": "modified corn starch",
    "highfructosecornsyrup": "high fructose corn syrup"
}
